name: "web_app"
mode: "dev"
port: 8081
version: "0.0.1"
start_time: "2007-01-02"
machine_id: 1
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backips: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "19174cxz.NB"
  dbname: "ttms"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "47.109.18.117"
  port: 7963
  db: 0
  password: 123654
  pool_size: 2

auth:
  jwt_expire: 8760